name: cfn-lint
on:
  push:
    paths:
      - 'stacks/*'
  pull_request:
    paths:
      - 'stacks/*'
jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install cfn-lint
      - run: make cfn-lint
